"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-01-01 00:00:00

Hand-written (not autogenerated) to mirror app/models/*.py exactly —
this is the migration equivalent of EFSOP-Part3-Database-Design.md.
Departments and Employees are mutually referential (a department has an
optional head employee; every employee belongs to a department), so
`departments.head_employee_id` is created without its foreign key and the
constraint is added after `employees` exists — the same use_alter pattern
the ORM model declares.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

EMPLOYEE_ROLE = sa.Enum(
    "TeachingAssistant", "Staff", "HeadOfDepartment", "ViceDean", "Admin", name="employeerole"
)
EMPLOYMENT_STATUS = sa.Enum("Active", "Inactive", name="employmentstatus")
LEAVE_REQUEST_STATUS = sa.Enum(
    "PendingStage1", "PendingStage2", "Approved", "Rejected", "Cancelled", name="leaverequeststatus"
)
APPROVAL_STEP_STATUS = sa.Enum("Pending", "Approved", "Rejected", "Skipped", name="approvalstepstatus")
OFFICIAL_DUTY_STATUS = sa.Enum("Pending", "Approved", "Rejected", name="officialdutystatus")
NOTIFICATION_CHANNEL = sa.Enum("Email", "InApp", name="notificationchannel")
NOTIFICATION_STATUS = sa.Enum("Sent", "Failed", "SkippedNoSmtp", name="notificationstatus")


def upgrade() -> None:
    # --- departments (head_employee_id FK added later, see module docstring) ---
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("code", sa.String(16), nullable=False),
        sa.Column("name_en", sa.String(200), nullable=False),
        sa.Column("name_ar", sa.String(200), nullable=False),
        sa.Column("head_employee_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_departments_code", "departments", ["code"], unique=True)

    # --- programs ---
    op.create_table(
        "programs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("code", sa.String(16), nullable=False),
        sa.Column("name_en", sa.String(200), nullable=False),
        sa.Column("name_ar", sa.String(200), nullable=False),
        sa.Column("department_id", sa.Integer(), sa.ForeignKey("departments.id"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.create_index("ix_programs_code", "programs", ["code"], unique=True)

    # --- employees ---
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("employee_code", sa.String(32), nullable=False),
        sa.Column("full_name_en", sa.String(200), nullable=False),
        sa.Column("full_name_ar", sa.String(200), nullable=False),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        sa.Column("department_id", sa.Integer(), sa.ForeignKey("departments.id"), nullable=False),
        sa.Column("program_id", sa.Integer(), sa.ForeignKey("programs.id"), nullable=True),
        sa.Column("academic_rank", sa.String(100), nullable=True),
        sa.Column("role", EMPLOYEE_ROLE, nullable=False),
        sa.Column("employment_status", EMPLOYMENT_STATUS, nullable=False, server_default="Active"),
        sa.Column("supervisor_id", sa.Integer(), sa.ForeignKey("employees.id"), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_employees_employee_code", "employees", ["employee_code"], unique=True)
    op.create_index("ix_employees_email", "employees", ["email"], unique=True)

    op.create_foreign_key(
        "fk_department_head", "departments", "employees", ["head_employee_id"], ["id"]
    )

    # --- leave_types ---
    op.create_table(
        "leave_types",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("code", sa.String(64), nullable=False),
        sa.Column("name_en", sa.String(200), nullable=False),
        sa.Column("name_ar", sa.String(200), nullable=False),
        sa.Column("annual_cap", sa.Integer(), nullable=False),
        sa.Column("max_consecutive_days", sa.Integer(), nullable=False),
        sa.Column("deducts_from_annual", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.create_index("ix_leave_types_code", "leave_types", ["code"], unique=True)

    # --- leave_balances ---
    op.create_table(
        "leave_balances",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("employee_id", sa.Integer(), sa.ForeignKey("employees.id"), nullable=False),
        sa.Column("leave_type_id", sa.Integer(), sa.ForeignKey("leave_types.id"), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("entitled_days", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("used_days", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("pending_days", sa.Integer(), nullable=False, server_default="0"),
        sa.UniqueConstraint("employee_id", "leave_type_id", "year", name="uq_balance_person_type_year"),
    )

    # --- leave_requests ---
    op.create_table(
        "leave_requests",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("request_key", sa.String(32), nullable=False),
        sa.Column("submission_id", sa.String(64), nullable=False),
        sa.Column("applicant_id", sa.Integer(), sa.ForeignKey("employees.id"), nullable=False),
        sa.Column("applicant_role", EMPLOYEE_ROLE, nullable=False),
        sa.Column("department_id", sa.Integer(), sa.ForeignKey("departments.id"), nullable=False),
        sa.Column("leave_type_id", sa.Integer(), sa.ForeignKey("leave_types.id"), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("request_year", sa.Integer(), nullable=False),
        sa.Column("working_days", sa.Integer(), nullable=False),
        sa.Column("substitute_id", sa.Integer(), sa.ForeignKey("employees.id"), nullable=True),
        sa.Column("substitute_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("substitute_objection", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", LEAVE_REQUEST_STATUS, nullable=False, server_default="PendingStage1"),
        sa.Column("current_stage", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("correlation_id", sa.String(64), nullable=False),
    )
    op.create_index("ix_leave_requests_request_key", "leave_requests", ["request_key"], unique=True)
    op.create_index("ix_leave_requests_submission_id", "leave_requests", ["submission_id"], unique=True)
    op.create_index("ix_leave_requests_status", "leave_requests", ["status"])

    # --- approval_steps ---
    op.create_table(
        "approval_steps",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("request_id", sa.Integer(), sa.ForeignKey("leave_requests.id"), nullable=False),
        sa.Column("stage_number", sa.Integer(), nullable=False),
        sa.Column("stage_name", sa.String(32), nullable=False),
        sa.Column("assigned_to_id", sa.Integer(), sa.ForeignKey("employees.id"), nullable=True),
        sa.Column("delegated_from_id", sa.Integer(), sa.ForeignKey("employees.id"), nullable=True),
        sa.Column("status", APPROVAL_STEP_STATUS, nullable=False, server_default="Pending"),
        sa.Column("sla_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("escalation_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_reminder_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
    )
    op.create_index("ix_approval_steps_status", "approval_steps", ["status"])

    # --- approval_routes ---
    op.create_table(
        "approval_routes",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("stage_number", sa.Integer(), nullable=False),
        sa.Column("stage_name", sa.String(32), nullable=False),
        sa.Column("role_required", EMPLOYEE_ROLE, nullable=False),
        sa.Column("sla_hours", sa.Integer(), nullable=False),
        sa.Column("escalation_hours", sa.Integer(), nullable=False),
        sa.UniqueConstraint("stage_number", name="uq_approval_routes_stage_number"),
    )

    # --- approval_delegations ---
    op.create_table(
        "approval_delegations",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("from_employee_id", sa.Integer(), sa.ForeignKey("employees.id"), nullable=False),
        sa.Column("to_employee_id", sa.Integer(), sa.ForeignKey("employees.id"), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )

    # --- official_duties ---
    op.create_table(
        "official_duties",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("duty_key", sa.String(32), nullable=False),
        sa.Column("owner_id", sa.Integer(), sa.ForeignKey("employees.id"), nullable=False),
        sa.Column("department_id", sa.Integer(), sa.ForeignKey("departments.id"), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("duty_year", sa.Integer(), nullable=False),
        sa.Column("working_days", sa.Integer(), nullable=False),
        sa.Column("destination", sa.String(255), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("evidence_url", sa.String(500), nullable=True),
        sa.Column("is_retroactive", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("retro_justification", sa.Text(), nullable=True),
        sa.Column("status", OFFICIAL_DUTY_STATUS, nullable=False, server_default="Pending"),
        sa.Column("approved_by_id", sa.Integer(), sa.ForeignKey("employees.id"), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_official_duties_duty_key", "official_duties", ["duty_key"], unique=True)
    op.create_index("ix_official_duties_status", "official_duties", ["status"])

    # --- holidays ---
    op.create_table(
        "holidays",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("holiday_date", sa.Date(), nullable=False),
        sa.Column("name_en", sa.String(200), nullable=False),
        sa.Column("name_ar", sa.String(200), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
    )
    op.create_index("ix_holidays_holiday_date", "holidays", ["holiday_date"], unique=True)
    op.create_index("ix_holidays_year", "holidays", ["year"])

    # --- app_settings ---
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("key", sa.String(100), nullable=False),
        sa.Column("value", sa.String(500), nullable=False),
        sa.Column("description", sa.String(500), nullable=True),
    )
    op.create_index("ix_app_settings_key", "app_settings", ["key"], unique=True)

    # --- audit_log ---
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("entity_type", sa.String(64), nullable=False),
        sa.Column("entity_key", sa.String(64), nullable=False),
        sa.Column("action", sa.String(64), nullable=False),
        sa.Column("claimed_actor_email", sa.String(255), nullable=True),
        sa.Column("resolved_actor_id", sa.Integer(), sa.ForeignKey("employees.id"), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.String(64), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_audit_log_entity_type", "audit_log", ["entity_type"])
    op.create_index("ix_audit_log_entity_key", "audit_log", ["entity_key"])
    op.create_index("ix_audit_log_occurred_at", "audit_log", ["occurred_at"])

    # --- notification_log ---
    op.create_table(
        "notification_log",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("recipient_email", sa.String(255), nullable=False),
        sa.Column("channel", NOTIFICATION_CHANNEL, nullable=False),
        sa.Column("template_key", sa.String(100), nullable=False),
        sa.Column("subject", sa.String(300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", NOTIFICATION_STATUS, nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_notification_log_recipient_email", "notification_log", ["recipient_email"])


def downgrade() -> None:
    op.drop_table("notification_log")
    op.drop_table("audit_log")
    op.drop_table("app_settings")
    op.drop_table("holidays")
    op.drop_table("official_duties")
    op.drop_table("approval_delegations")
    op.drop_table("approval_routes")
    op.drop_table("approval_steps")
    op.drop_table("leave_requests")
    op.drop_table("leave_balances")
    op.drop_table("leave_types")
    op.drop_constraint("fk_department_head", "departments", type_="foreignkey")
    op.drop_table("employees")
    op.drop_table("programs")
    op.drop_table("departments")
